version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    # Look for NuGet dependency info from the `root` directory
    directory: "/"
    # Check the nuget registry for updates every day (weekdays) schedule:
    schedule:
      interval: "daily"
