pull_request_rules:
  - name: automatic merge on CI success for updates from bots
    conditions:
      - check-success=Evaluate flake.nix
      - check-success=check format [x86-64-linux]
      - check-success=nixosConfig beherbergung-lifeline
      - check-success=nixosConfig beherbergung-warhelp
      - check-success=nixosConfig vm
      - check-success=Evaluate flake.nix
      - check-success=check deadnix [x86-64-linux]
      - check-success=check nixos-test [x86-64-linux]
      - check-success=package updateBackendDeps [x86-64-linux]
      - check-success=package updateFrontendDeps [x86-64-linux]
      - check-success=package beherbergung-backend [x86-64-linux]
      - check-success=package beherbergung-frontend-assets [x86-64-linux]
      - check-success=package beherbergung-frontend-deps [x86-64-linux]
      - check-success=package beherbergung-fullstack [x86-64-linux]
      - check-success=package devShell [x86-64-linux]
      - or:
        - author=dependabot[bot]
        - author=nix-eval-jobs-bot
      - base=main
    actions:
      merge:
        method: merge
      delete_head_branch: {}
