[formatter.nix]
command = "alejandra"
includes = ["*.nix"]

# TODO
#[formatter.clojure]
#command = "sh"
#options = [
#  "-euc",
#  """
#  cd backend
#  clj-kondo --lint "$@"
#"""
#]
#includes = ["*.clj"]

[formatter.shell]
command = "sh"
options = [
    "-eucx",
    """
# This is a bug in treefmt, the script should not be called without arguments
if [[ $# -le 0 ]]; then exit 0; fi
# First shellcheck
shellcheck --external-sources --source-path=SCRIPTDIR "$@"
# Then format
shfmt -i 2 -s -w "$@"
    """
]
includes = ["*.sh"]
excludes = []

[formatter.prettier]
command = "prettier"
options = ["--write"]
includes = [
    "*.css",
    "*.html",
    "*.js",
    "*.json",
    "*.jsx",
    "*.md",
    "*.mdx",
    "*.scss",
    "*.ts",
]
